name: viztube
base: core22
version: '2025.12.17'
summary: Download youtube videos, playlist and music audio in full HD formats
description: VIZTUBE is a powerful GUI application for linux for downloading youtube videos, playlist and music audio in full UHD+ resolutions and supports MP4, WEBM and MP3 formats.
grade: stable
confinement: strict

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/content-snap-core22

apps:
  viztube:
    command: bin/desktop-launch viztube
    desktop: viztube.desktop
    environment:
      DISABLE_WAYLAND: 1

    plugs:
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - audio-playback
       - hardware-observe
       - optical-drive
       - removable-media

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  content-snap-core22:
    interface: content
    target: $SNAP/content-snap-core22
    default-provider: content-snap-core22

parts:
  deno:
    plugin: nil
    source: https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip
    source-type: zip
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp deno $SNAPCRAFT_PART_INSTALL/bin/deno
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/deno

  snap-launcher:
    plugin: dump
    source: snap_launcher/
    override-build: |
      craftctl default
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/viztube.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/viztube.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/viztube.desktop

  viztube-binary:
    plugin: dump
    source: https://warlordsoftwares.com/static/app_builds/snap/VIZTUBE.tar.gz
    source-type: tar
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin
      cp VIZTUBE ${SNAPCRAFT_PART_INSTALL}/bin/viztube
      chmod +x ${SNAPCRAFT_PART_INSTALL}/bin/viztube
      
